apiVersion: v1
kind: Service
metadata:
  name: tyk-gtw-internal-svc
  namespace: tyk-system
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: gateway-tyk-gateway-tyk-headless
    release: tyk-gateway