apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: tyk-gtw-pvc
  name: tyk-gtw-pvc
  namespace: tyk-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard
  volumeMode: Filesystem